"""Extend user model with encrypted fields

Revision ID: 2f23a180800e
Revises: 30e5680e7713
Create Date: 2025-04-21 19:59:54.787033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f23a180800e'
down_revision = '30e5680e7713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('document_number', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('birth_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('eps', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('blood_type', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('two_factor_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_code', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('gender')
        batch_op.drop_column('allergies')
        batch_op.drop_column('blood_type')
        batch_op.drop_column('eps')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('document_number')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
